// Auto-generated by ChainCSS Vite Plugin
// DO NOT EDIT

export const body = 'chain-body'
export const btnOutline = 'chain-btn-outline'
export const btnPrimary = 'chain-btn-primary'
export const ctaSection = 'chain-cta-section'
export const featureCard = 'chain-feature-card'
export const featureIcon = 'chain-feature-icon'
export const h1 = 'chain-h1'
export const h2 = 'chain-h2'
export const navbar = 'chain-navbar'
export const pricingCard = 'chain-pricing-card'
export const pricingCardFeatured = 'chain-pricing-card-featured'
export const subtitle = 'chain-section-subtitle'