import { chain } from 'chaincss'

// ============================================================
// Design Tokens
// ============================================================
const colors = {
  primary: '#6366f1',
  primaryDark: '#4f46e5',
  bg: '#0f172a',
  bgCard: '#1e293b',
  bgCardHover: '#334155',
  text: '#f1f5f9',
  textMuted: '#94a3b8',
  border: '#334155',
  white: '#ffffff',
}

// ============================================================
// Buttons
// ============================================================
export const btnPrimary = chain()
  .bg(colors.primary)
  .color(colors.white)
  .padding('12px 24px')
  .rounded(8)
  .fontSize(16)
  .fontWeight(600)
  .display('inline-flex')
  .alignItems('center')
  .gap(8)
  .cursor('pointer')
  .border('none')
  .transition('all 0.2s ease')
  .textDecoration('none')
  .hover()
    .bg(colors.primaryDark)
    .transform('translateY(-1px)')
    .shadow('0 4px 12px rgba(99,102,241,0.4)')
  .end()
  .$el('btn-primary')

export const btnOutline = chain()
  .bg('transparent')
  .color(colors.text)
  .padding('12px 24px')
  .rounded(8)
  .fontSize(16)
  .fontWeight(600)
  .display('inline-flex')
  .alignItems('center')
  .gap(8)
  .cursor('pointer')
  .border(`2px solid ${colors.border}`)
  .transition('all 0.2s ease')
  .textDecoration('none')
  .hover()
    .border(`2px solid ${colors.primary}`)
    .color(colors.primary)
  .end()
  .$el('btn-outline')

// ============================================================
// Feature Cards
// ============================================================
export const featureCard = chain()
  .bg(colors.bgCard)
  .padding(32)
  .rounded(12)
  .border(`1px solid ${colors.border}`)
  .transition('all 0.3s ease')
  .hover()
    .bg(colors.bgCardHover)
    .transform('translateY(-4px)')
    .shadow('0 8px 30px rgba(0,0,0,0.3)')
  .end()
  .$el('feature-card')

export const featureIcon = chain()
  .fontSize(32)
  .marginBottom(16)
  .display('block')
  .$el('feature-icon')

// ============================================================
// Pricing Cards
// ============================================================
export const pricingCard = chain()
  .bg(colors.bgCard)
  .padding(40)
  .rounded(16)
  .border(`1px solid ${colors.border}`)
  .display('flex')
  .flexDirection('column')
  .gap(20)
  .transition('all 0.3s ease')
  .hover()
    .border(`1px solid ${colors.primary}`)
    .transform('translateY(-4px)')
  .end()
  .$el('pricing-card')

export const pricingCardFeatured = chain()
  .bg(`linear-gradient(135deg, ${colors.primary}, #8b5cf6)`)
  .padding(40)
  .rounded(16)
  .border(`2px solid ${colors.primary}`)
  .display('flex')
  .flexDirection('column')
  .gap(20)
  .position('relative')
  .transform('scale(1.05)')
  .shadow('0 12px 40px rgba(99,102,241,0.3)')
  .$el('pricing-card-featured')

// ============================================================
// CTA Section
// ============================================================
export const ctaSection = chain()
  .bg(`linear-gradient(135deg, ${colors.primary}, #8b5cf6)`)
  .padding('80px 24px')
  .textAlign('center')
  .rounded(24)
  .margin('60px auto')
  .maxW(900)
  .$el('cta-section')

// ============================================================
// Navbar
// ============================================================
export const navbar = chain()
  .bg('rgba(15,23,42,0.95)')
  .backdropFilter('blur(20px)')
  .borderBottom(`1px solid ${colors.border}`)
  .position('sticky')
  .top(0)
  .z(100)
  .padding('16px 0')
  .$el('navbar')

// ============================================================
// Global Styles
// ============================================================
export const body = chain()
  .bg(colors.bg)
  .color(colors.text)
  .fontFamily("'Inter', system-ui, -apple-system, sans-serif")
  .margin(0)
  .padding(0)
  .minHeight('100vh')
  .$el('body')

// Typography
export const h1 = chain()
  .fontSize(56)
  .fontWeight(800)
  .lineHeight(1.1)
  .marginBottom(24)
  .letterSpacing('-0.02em')
  .$el('h1')

export const h2 = chain()
  .fontSize(40)
  .fontWeight(700)
  .lineHeight(1.2)
  .marginBottom(16)
  .letterSpacing('-0.01em')
  .$el('h2')

export const subtitle = chain()
  .fontSize(18)
  .color(colors.textMuted)
  .lineHeight(1.6)
  .maxW(600)
  .marginBottom(48)
  .$el('section-subtitle')

// ============================================================
// Extended Component Library (50+ components)
// ============================================================

// Badges
export const badge = chain()
  .display('inline-flex')
  .alignItems('center')
  .padding('4px 12px')
  .rounded(20)
  .fontSize(12)
  .fontWeight(600)
  .bg(colors.primary)
  .color(colors.white)
  .$el('badge')

export const badgeOutline = chain()
  .display('inline-flex')
  .alignItems('center')
  .padding('4px 12px')
  .rounded(20)
  .fontSize(12)
  .fontWeight(600)
  .bg('transparent')
  .color(colors.primary)
  .border(`1px solid ${colors.primary}`)
  .$el('badge-outline')

// Avatar
export const avatar = chain()
  .w(40).h(40).rounded('50%')
  .bg(colors.bgCard)
  .display('inline-flex')
  .alignItems('center')
  .justifyContent('center')
  .fontSize(16)
  .fontWeight(700)
  .color(colors.text)
  .overflow('hidden')
  .$el('avatar')

export const avatarLg = chain()
  .w(64).h(64).rounded('50%')
  .bg(colors.bgCard)
  .display('inline-flex')
  .alignItems('center')
  .justifyContent('center')
  .fontSize(24)
  .fontWeight(700)
  .color(colors.text)
  .overflow('hidden')
  .$el('avatar-lg')

// Input
export const input = chain()
  .bg(colors.bgCard)
  .color(colors.text)
  .padding('12px 16px')
  .rounded(8)
  .border(`1px solid ${colors.border}`)
  .fontSize(14)
  .width('100%')
  .transition('border-color 0.2s ease')
  .placeholderColor(colors.textMuted)
  .focus()
    .borderColor(colors.primary)
    .outline('none')
    .shadow(`0 0 0 3px rgba(99,102,241,0.2)`)
  .end()
  .$el('input')

export const textarea = chain()
  .bg(colors.bgCard)
  .color(colors.text)
  .padding('12px 16px')
  .rounded(8)
  .border(`1px solid ${colors.border}`)
  .fontSize(14)
  .width('100%')
  .minHeight(100)
  .resize('vertical')
  .$el('textarea')

// Select
export const select = chain()
  .bg(colors.bgCard)
  .color(colors.text)
  .padding('12px 16px')
  .rounded(8)
  .border(`1px solid ${colors.border}`)
  .fontSize(14)
  .width('100%')
  .cursor('pointer')
  .appearance('none')
  .$el('select')

// Checkbox & Radio
export const checkbox = chain()
  .w(18).h(18)
  .accentColor(colors.primary)
  .cursor('pointer')
  .$el('checkbox')

export const radio = chain()
  .w(18).h(18)
  .accentColor(colors.primary)
  .cursor('pointer')
  .$el('radio')

// Toggle Switch
export const toggle = chain()
  .w(44).h(24)
  .bg(colors.border)
  .rounded(12)
  .position('relative')
  .cursor('pointer')
  .transition('background 0.2s')
  .appearance('none')
  .checked()
    .bg(colors.primary)
  .end()
  .$el('toggle')

// Labels
export const label = chain()
  .fontSize(14)
  .fontWeight(500)
  .color(colors.text)
  .marginBottom(6)
  .display('block')
  .$el('label')

// Helper text
export const helperText = chain()
  .fontSize(12)
  .color(colors.textMuted)
  .marginTop(4)
  .$el('helper-text')

// Alert / Notification
export const alert = chain()
  .padding('16px 20px')
  .rounded(8)
  .border('1px solid')
  .fontSize(14)
  .display('flex')
  .alignItems('flex-start')
  .gap(12)
  .$el('alert')

export const alertSuccess = chain()
  .padding('16px 20px')
  .rounded(8)
  .bg('rgba(34,197,94,0.1)')
  .border('1px solid rgba(34,197,94,0.3)')
  .color('#22c55e')
  .fontSize(14)
  .$el('alert-success')

export const alertWarning = chain()
  .padding('16px 20px')
  .rounded(8)
  .bg('rgba(234,179,8,0.1)')
  .border('1px solid rgba(234,179,8,0.3)')
  .color('#eab308')
  .fontSize(14)
  .$el('alert-warning')

export const alertError = chain()
  .padding('16px 20px')
  .rounded(8)
  .bg('rgba(239,68,68,0.1)')
  .border('1px solid rgba(239,68,68,0.3)')
  .color('#ef4444')
  .fontSize(14)
  .$el('alert-error')

// Modal
export const modalOverlay = chain()
  .position('fixed')
  .inset(0)
  .bg('rgba(0,0,0,0.6)')
  .display('flex')
  .alignItems('center')
  .justifyContent('center')
  .z(1000)
  .backdropFilter('blur(4px)')
  .$el('modal-overlay')

export const modalContent = chain()
  .bg(colors.bg)
  .padding(32)
  .rounded(16)
  .border(`1px solid ${colors.border}`)
  .maxW(500)
  .width('90%')
  .shadow('0 20px 60px rgba(0,0,0,0.5)')
  .$el('modal-content')

// Toast
export const toast = chain()
  .position('fixed')
  .bottom(24).right(24)
  .bg(colors.bgCard)
  .color(colors.text)
  .padding('16px 24px')
  .rounded(12)
  .border(`1px solid ${colors.border}`)
  .shadow('0 8px 32px rgba(0,0,0,0.4)')
  .z(1100)
  .fontSize(14)
  .display('flex')
  .alignItems('center')
  .gap(12)
  .animation('slideIn 0.3s ease')
  .$el('toast')

// Tooltip
export const tooltip = chain()
  .bg(colors.text)
  .color(colors.bg)
  .padding('6px 12px')
  .rounded(6)
  .fontSize(12)
  .fontWeight(500)
  .position('absolute')
  .z(900)
  .pointerEvents('none')
  .$el('tooltip')

// Dropdown Menu
export const dropdownMenu = chain()
  .bg(colors.bgCard)
  .border(`1px solid ${colors.border}`)
  .rounded(8)
  .padding('8px 0')
  .shadow('0 8px 32px rgba(0,0,0,0.3)')
  .minWidth(180)
  .z(800)
  .$el('dropdown-menu')

export const dropdownItem = chain()
  .padding('8px 16px')
  .fontSize(14)
  .color(colors.text)
  .cursor('pointer')
  .transition('background 0.15s')
  .display('block')
  .textDecoration('none')
  .hover()
    .bg(colors.bgCardHover)
  .end()
  .$el('dropdown-item')

// Table
export const table = chain()
  .width('100%')
  .borderCollapse('collapse')
  .$el('table')

export const th = chain()
  .padding('12px 16px')
  .textAlign('left')
  .fontSize(12)
  .fontWeight(600)
  .color(colors.textMuted)
  .borderBottom(`2px solid ${colors.border}`)
  .$el('th')

export const td = chain()
  .padding('12px 16px')
  .fontSize(14)
  .borderBottom(`1px solid ${colors.border}`)
  .$el('td')

// Tabs
export const tabs = chain()
  .display('flex')
  .borderBottom(`2px solid ${colors.border}`)
  .gap(0)
  .$el('tabs')

export const tabItem = chain()
  .padding('12px 20px')
  .fontSize(14)
  .fontWeight(500)
  .color(colors.textMuted)
  .cursor('pointer')
  .borderBottom('2px solid transparent')
  .marginBottom('-2px')
  .transition('all 0.2s')
  .hover()
    .color(colors.text)
  .end()
  .$el('tab-item')

export const tabItemActive = chain()
  .padding('12px 20px')
  .fontSize(14)
  .fontWeight(600)
  .color(colors.primary)
  .cursor('pointer')
  .borderBottom(`2px solid ${colors.primary}`)
  .marginBottom('-2px')
  .$el('tab-item-active')

// Breadcrumb
export const breadcrumb = chain()
  .display('flex')
  .alignItems('center')
  .gap(8)
  .fontSize(14)
  .color(colors.textMuted)
  .$el('breadcrumb')

// Pagination
export const pagination = chain()
  .display('flex')
  .alignItems('center')
  .gap(4)
  .$el('pagination')

export const pageItem = chain()
  .w(36).h(36)
  .display('flex')
  .alignItems('center')
  .justifyContent('center')
  .rounded(8)
  .fontSize(14)
  .cursor('pointer')
  .transition('all 0.2s')
  .hover()
    .bg(colors.bgCardHover)
  .end()
  .$el('page-item')

export const pageItemActive = chain()
  .w(36).h(36)
  .display('flex')
  .alignItems('center')
  .justifyContent('center')
  .rounded(8)
  .fontSize(14)
  .fontWeight(600)
  .bg(colors.primary)
  .color(colors.white)
  .$el('page-item-active')

// Skeleton
export const skeleton = chain()
  .bg(colors.bgCardHover)
  .rounded(8)
  .animation('pulse 1.5s ease-in-out infinite')
  .$el('skeleton')

export const skeletonText = chain()
  .bg(colors.bgCardHover)
  .rounded(4)
  .height(14)
  .animation('pulse 1.5s ease-in-out infinite')
  .$el('skeleton-text')

// Divider
export const divider = chain()
  .height(1)
  .bg(colors.border)
  .width('100%')
  .margin('16px 0')
  .border('none')
  .$el('divider')

// Container
export const container = chain()
  .maxW(1200)
  .margin('0 auto')
  .padding('0 24px')
  .width('100%')
  .$el('container')

// Stack layouts
export const hStack = chain()
  .display('flex')
  .alignItems('center')
  .gap(16)
  .$el('hstack')

export const vStack = chain()
  .display('flex')
  .flexDirection('column')
  .gap(16)
  .$el('vstack')

export const grid = chain()
  .display('grid')
  .gap(24)
  .$el('grid')

// Spinner
export const spinner = chain()
  .w(24).h(24)
  .border('3px solid')
  .borderColor(colors.border)
  .borderTopColor(colors.primary)
  .rounded('50%')
  .animation('spin 0.6s linear infinite')
  .$el('spinner')

// Progress bar
export const progressBar = chain()
  .width('100%')
  .height(6)
  .bg(colors.border)
  .rounded(3)
  .overflow('hidden')
  .$el('progress-bar')

export const progressFill = chain()
  .height('100%')
  .bg(colors.primary)
  .rounded(3)
  .transition('width 0.3s ease')
  .$el('progress-fill')

// Empty state
export const emptyState = chain()
  .display('flex')
  .flexDirection('column')
  .alignItems('center')
  .justifyContent('center')
  .padding('60px 24px')
  .textAlign('center')
  .color(colors.textMuted)
  .$el('empty-state')
